spring:
  application:
    name: kopring
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

application:
  title: Org Gcloud API
  version: 1.0.0

message: Hello from Default Profile!

logging:
  level:
    org.springframework: debug


---
# -Dspring.profiles.active=prod
spring:
  config:
    activate:
      on-profile: prod

message: Hello from Production Profile!

---
spring:
  config:
    activate:
      on-profile: test

message: Hello from Test Profile!
