services:
  postgresql:
    image: postgres:15
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: simppl
      POSTGRES_PASSWORD: simppl
      POSTGRES_SCHEMA: local
      TZ: Asia/Seoul
    restart: always
    volumes:
      - ./etc/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ${SIMPPL_NETWORK}
