spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

---
spring.config.activate.on-profile:
  - develop
  - production

spring:
  datasource:
    url: jdbc:postgresql://${SIMPPL_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SIMPPL_DB_USERNAME}
    password: ${SIMPPL_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${SIMPPL_DB_POOL_SIZE}
      connection-timeout: ${SIMPPL_DB_CONNECTION_TIMEOUT}
      keepalive-time: ${SIMPPL_DB_KEEPALIVE_TIME}
      validation-timeout: ${SIMPPL_DB_VALIDATION_TIMEOUT}
