spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: localhost
      port: 6379

---
spring.config.activate.on-profile:
  - develop
  - production

spring:
  data:
    redis:
      host: ${SIMPPL_REDIS_HOST}
      port: ${SIMPPL_REDIS_PORT}
