spring.application.name: simppl-api
spring.profiles.default: local
spring:
  config.import:
  - application-db.yaml
  - application-swagger.yaml
  - application-redis.yaml
  - application-monitoring.yaml
  security:
    user:
      password: 1

server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

app:
  auth:
    token-secret: simppl-api-local-token-secret-not-use-in-production
    token-timeout-ms: 3600000
    refresh-token-timeout-ms: 86400000
  cors:
    allowed-origins: "*"
