spring:
  application.name: springsecurity
#  security:
#    user:
#      name: root
#      password: root
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
logging:
  level:
    org.springframework: info

server:
  servlet:
    session:
      cookie:
        same-site: strict
